### PR TITLE
Update Rviz configuration

### LINKED ISSUE #315: Update rviz configuration for the car
The robot model should be visible

### PR DESCRIPTION
**Pull request by marian42**
Also changes the default position of the keyboard controller.
Fixes #315

### CODE REVIEW

**Comment by marian42** [comment]
Did you run `catkin_make`? :thinking:

**Comment by StefanJVA** [comment]
> Did you run `catkin_make`? thinking

Sure! I even removed /devel and /build and started from scratch.

**Comment by StefanJVA** [comment]
> > Did you run `catkin_make`? thinking
> 
> Sure! I even removed /devel and /build and started from scratch.

Okay, got it. Was still my fold :D it works now!

**Comment by StefanJVA** [comment]
> > > Did you run `catkin_make`? thinking
> > 
> > 
> > Sure! I even removed /devel and /build and started from scratch.
> 
> Okay, got it. Was still my fold :D it works now!

Multiple instances of the same repo are a very bad idea for ros :D

**Pull request merged**
